"""商户分类配置

统一管理所有商户分类规则，支持多种匹配策略
"""

MERCHANT_CATEGORIES = {
    # 精确匹配规则 - 最高优先级
    'exact_match': {
        # 餐饮类
        '麦当劳': 'dining',
        '肯德基': 'dining',
        '星巴克': 'dining',
        '必胜客': 'dining',
        '德克士': 'dining',
        '黄焖鸡餐厅': 'dining',
        '兰州拉面': 'dining',
        '沙县小吃': 'dining',
        '华莱士': 'dining',
        '真功夫': 'dining',
        '永和大王': 'dining',
        '吉野家': 'dining',
        '味千拉面': 'dining',
        '海底捞': 'dining',
        '呷哺呷哺': 'dining',
        '小肥羊': 'dining',
        '外婆家': 'dining',
        '绿茶餐厅': 'dining',
        '西贝莜面村': 'dining',
        '云海肴': 'dining',
        '太二酸菜鱼': 'dining',
        '喜茶': 'dining',
        '奈雪的茶': 'dining',
        '一点点': 'dining',
        'CoCo都可': 'dining',
        '蜜雪冰城': 'dining',
        '瑞幸咖啡': 'dining',
        'costa咖啡': 'dining',
        '太平洋咖啡': 'dining',
        
        # 交通类
        '滴滴出行': 'transport',
        '深圳通': 'transport',
        '羊城通': 'transport',
        '北京一卡通': 'transport',
        '上海公共交通卡': 'transport',
        '中国石油': 'transport',
        '中国石化': 'transport',
        '壳牌': 'transport',
        '美孚': 'transport',
        '首汽约车': 'transport',
        '神州专车': 'transport',
        '曹操出行': 'transport',
        '哈啰出行': 'transport',
        '青桔单车': 'transport',
        '摩拜单车': 'transport',
        'ofo小黄车': 'transport',
        '12306': 'transport',
        '携程': 'transport',
        '去哪儿': 'transport',
        '飞猪': 'transport',
        
        # 购物类
        '京东': 'shopping',
        '淘宝': 'shopping',
        '天猫': 'shopping',
        '拼多多': 'shopping',
        '苏宁易购': 'shopping',
        '国美': 'shopping',
        '永辉超市': 'shopping',
        '华润万家': 'shopping',
        '家乐福': 'shopping',
        '沃尔玛': 'shopping',
        '大润发': 'shopping',
        '物美': 'shopping',
        '7-11': 'shopping',
        '全家': 'shopping',
        '罗森': 'shopping',
        '便利蜂': 'shopping',
        '万达广场': 'shopping',
        '银泰百货': 'shopping',
        '王府井': 'shopping',
        '新世界': 'shopping',
        '太古汇': 'shopping',
        '海港城': 'shopping',
        '宜家': 'shopping',
        '红星美凯龙': 'shopping',
        '居然之家': 'shopping',
        
        # 生活服务类
        '中国移动': 'services',
        '中国联通': 'services',
        '中国电信': 'services',
        '广电网络': 'services',
        '长城宽带': 'services',
        '顺丰速运': 'services',
        '圆通速递': 'services',
        '申通快递': 'services',
        '中通快递': 'services',
        '韵达快递': 'services',
        '百世汇通': 'services',
        '德邦物流': 'services',
        'EMS': 'services',
        '美团': 'services',
        '饿了么': 'services',
        '大众点评': 'services',
        '58同城': 'services',
        '链家': 'services',
        '我爱我家': 'services',
        '中原地产': 'services',
        '21世纪不动产': 'services',
        '理发店': 'services',
        '美容院': 'services',
        '洗衣店': 'services',
        '修理店': 'services',
        
        # 医疗健康类
        '人民医院': 'healthcare',
        '中医院': 'healthcare',
        '第一人民医院': 'healthcare',
        '第二人民医院': 'healthcare',
        '妇幼保健院': 'healthcare',
        '儿童医院': 'healthcare',
        '同仁医院': 'healthcare',
        '协和医院': 'healthcare',
        '301医院': 'healthcare',
        '华西医院': 'healthcare',
        '湘雅医院': 'healthcare',
        '瑞金医院': 'healthcare',
        '华山医院': 'healthcare',
        '中山医院': 'healthcare',
        '仁济医院': 'healthcare',
        '九院': 'healthcare',
        '六院': 'healthcare',
        '同济医院': 'healthcare',
        '老百姓大药房': 'healthcare',
        '海王星辰': 'healthcare',
        '康之家': 'healthcare',
        '大参林': 'healthcare',
        '益丰大药房': 'healthcare',
        '一心堂': 'healthcare',
        '国药控股': 'healthcare',
        '华润医药': 'healthcare',
        '爱康国宾': 'healthcare',
        '美年大健康': 'healthcare',
        '慈铭体检': 'healthcare',
        
        # 金融保险类
        '中国人寿': 'finance',
        '平安保险': 'finance',
        '太平洋保险': 'finance',
        '新华保险': 'finance',
        '泰康人寿': 'finance',
        '人保财险': 'finance',
        '太平保险': 'finance',
        '阳光保险': 'finance',
        '华夏保险': 'finance',
        '友邦保险': 'finance',
        '工商银行': 'finance',
        '建设银行': 'finance',
        '农业银行': 'finance',
        '中国银行': 'finance',
        '交通银行': 'finance',
        '招商银行': 'finance',
        '中信银行': 'finance',
        '光大银行': 'finance',
        '华夏银行': 'finance',
        '民生银行': 'finance',
        '兴业银行': 'finance',
        '浦发银行': 'finance',
        '平安银行': 'finance',
        '广发银行': 'finance',
        '邮储银行': 'finance',
        '支付宝': 'finance',
        '微信支付': 'finance',
        '银联': 'finance',
        '网商银行': 'finance',
        '微众银行': 'finance',
    },
    
    # 关键词匹配规则 - 中等优先级
    'keyword_match': {
        '医院': 'healthcare',
        '药店': 'healthcare',
        '药房': 'healthcare',
        '诊所': 'healthcare',
        '体检': 'healthcare',
        '银行': 'finance',
        '保险': 'finance',
        '证券': 'finance',
        '基金': 'finance',
        '超市': 'shopping',
        '商场': 'shopping',
        '百货': 'shopping',
        '购物': 'shopping',
        '餐厅': 'dining',
        '咖啡': 'dining',
        '茶饮': 'dining',
        '火锅': 'dining',
        '烧烤': 'dining',
        '地铁': 'transport',
        '公交': 'transport',
        '出租': 'transport',
        '加油': 'transport',
        '停车': 'transport',
        '快递': 'services',
        '物流': 'services',
        '通信': 'services',
        '宽带': 'services',
        '理发': 'services',
        '美容': 'services',
    },
    
    # 模式匹配规则 - 最低优先级
    'pattern_match': [
        {'pattern': r'.*医院.*', 'category': 'healthcare'},
        {'pattern': r'.*药房.*', 'category': 'healthcare'},
        {'pattern': r'.*诊所.*', 'category': 'healthcare'},
        {'pattern': r'.*银行.*', 'category': 'finance'},
        {'pattern': r'.*保险.*', 'category': 'finance'},
        {'pattern': r'.*证券.*', 'category': 'finance'},
        {'pattern': r'.*超市.*', 'category': 'shopping'},
        {'pattern': r'.*商城.*', 'category': 'shopping'},
        {'pattern': r'.*商场.*', 'category': 'shopping'},
        {'pattern': r'.*餐厅.*', 'category': 'dining'},
        {'pattern': r'.*咖啡.*', 'category': 'dining'},
        {'pattern': r'.*茶.*', 'category': 'dining'},
        {'pattern': r'.*地铁.*', 'category': 'transport'},
        {'pattern': r'.*公交.*', 'category': 'transport'},
        {'pattern': r'.*出租.*', 'category': 'transport'},
        {'pattern': r'.*快递.*', 'category': 'services'},
        {'pattern': r'.*物流.*', 'category': 'services'},
        {'pattern': r'.*通信.*', 'category': 'services'},
    ]
}