# 商户分类配置文件
# 定义分类元数据和商户精确匹配映射

# 分类元数据定义
categories:
  dining:
    name: "餐饮支出"
    icon: "coffee"
    color: "primary"
    description: "餐厅、咖啡、外卖等饮食消费"
  transport:
    name: "交通支出"
    icon: "car"
    color: "success"
    description: "地铁、打车、加油等出行费用"
  shopping:
    name: "购物支出"
    icon: "shopping-bag"
    color: "info"
    description: "网购、超市、商场等购物消费"
  services:
    name: "生活服务"
    icon: "settings"
    color: "warning"
    description: "通信、快递、美容等服务费用"
  healthcare:
    name: "医疗健康"
    icon: "heart"
    color: "danger"
    description: "医院、药店、体检等医疗支出"
  finance:
    name: "金融保险"
    icon: "credit-card"
    color: "secondary"
    description: "保险、转账等金融相关支出"
  other:
    name: "其他支出"
    icon: "more-horizontal"
    color: "dark"
    description: "未分类的其他支出"

# 商户精确匹配映射
merchants:
  dining:
    # 中式餐厅
    - "黄焖鸡餐厅"
    - "兰州拉面"
    - "沙县小吃"
    - "煲仔饭"
    - "盖浇饭"
    - "小湘厨"
    - "潮汕汤粉"
    - "川菜馆"
    - "粤菜馆"
    - "湘菜馆"
    - "火锅店"
    - "烧烤店"
    - "小吃店"
    - "食堂"
    
    # 快餐连锁
    - "麦当劳"
    - "肯德基"
    - "汉堡王"
    - "德克士"
    - "华莱士"
    - "真功夫"
    - "永和大王"
    - "吉野家"
    - "味千拉面"
    
    # 咖啡茶饮
    - "星巴克"
    - "瑞幸咖啡"
    - "喜茶"
    - "奈雪的茶"
    - "蜜雪冰城"
    - "一点点"
    - "COCO都可"
    - "茶颜悦色"
    - "古茗"
    - "书亦烧仙草"
    
    # 外卖平台
    - "美团外卖"
    - "饿了么"
    - "百度外卖"
    
  transport:
    # 公共交通
    - "深圳通"
    - "羊城通"
    - "北京一卡通"
    - "上海公共交通卡"
    - "地铁"
    - "公交"
    - "轻轨"
    - "有轨电车"
    
    # 网约车
    - "滴滴出行"
    - "高德打车"
    - "曹操出行"
    - "T3出行"
    - "首汽约车"
    - "神州专车"
    - "易到用车"
    - "出租车"
    - "网约车"
    - "代驾"
    
    # 共享出行
    - "摩拜单车"
    - "哈啰出行"
    - "青桔单车"
    - "美团单车"
    - "共享单车"
    - "共享汽车"
    
    # 加油站
    - "中石油"
    - "中石化"
    - "中海油"
    - "壳牌"
    - "BP"
    - "道达尔"
    - "加油站"
    
    # 停车
    - "停车场"
    - "停车费"
    - "路边停车"
    - "智慧停车"
    
  shopping:
    # 电商平台
    - "京东"
    - "淘宝"
    - "天猫"
    - "拼多多"
    - "苏宁易购"
    - "国美在线"
    - "唯品会"
    - "当当网"
    - "亚马逊"
    
    # 超市便利店
    - "沃尔玛"
    - "家乐福"
    - "大润发"
    - "华润万家"
    - "永辉超市"
    - "物美"
    - "联华超市"
    - "7-11"
    - "全家"
    - "罗森"
    - "便利蜂"
    - "ACE"
    
    # 商场百货
    - "万象城"
    - "海岸城"
    - "天虹"
    - "万达广场"
    - "银泰百货"
    - "王府井"
    - "新世界百货"
    - "购物中心"
    - "商场"
    - "百货"
    
  services:
    # 通信服务
    - "中国移动"
    - "中国联通"
    - "中国电信"
    - "话费充值"
    - "流量充值"
    - "宽带费"
    - "网络费"
    
    # 快递物流
    - "顺丰速运"
    - "圆通速递"
    - "中通快递"
    - "申通快递"
    - "韵达快递"
    - "百世快递"
    - "德邦快递"
    - "京东物流"
    - "菜鸟驿站"
    - "丰巢"
    
    # 生活服务
    - "理发店"
    - "美容院"
    - "美甲店"
    - "洗衣店"
    - "干洗店"
    - "维修店"
    - "家政服务"
    - "搬家公司"
    
  healthcare:
    # 医疗机构
    - "人民医院"
    - "中医院"
    - "妇幼保健院"
    - "儿童医院"
    - "口腔医院"
    - "眼科医院"
    - "专科医院"
    - "诊所"
    - "社区卫生服务中心"
    - "体检中心"
    
    # 药店
    - "大参林"
    - "老百姓大药房"
    - "益丰大药房"
    - "一心堂"
    - "海王星辰"
    - "华氏大药房"
    - "药店"
    - "药房"
    
  finance:
    # 保险公司
    - "中国人寿"
    - "平安保险"
    - "太平洋保险"
    - "新华保险"
    - "泰康保险"
    - "阳光保险"
    - "华夏保险"
    - "人保财险"
    - "太平保险"
    
    # 银行服务
    - "工商银行"
    - "建设银行"
    - "农业银行"
    - "中国银行"
    - "交通银行"
    - "招商银行"
    - "中信银行"
    - "民生银行"
    - "浦发银行"
    - "兴业银行"
    - "光大银行"
    - "华夏银行"
    - "广发银行"
    - "平安银行"
    - "邮储银行"
    - "转账手续费"
    - "银行手续费"
